### EDA

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("customer_shopping_behavior.csv")
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [8]:
len(df)

5050

In [9]:
df.shape

(5050, 17)

In [11]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [13]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5050.000000,5050.000000,5050,5050,5050,4494.000000,5050,4680,5050,5050,4449.000000,5050,5050,5050,4502.000000,5050,5050
unique,NaN,NaN,3,30,5,NaN,54,4,25,5,NaN,2,6,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,NaN,NaN,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,2519.570891,44.150495,NaN,NaN,NaN,144.765236,NaN,NaN,NaN,NaN,3.668195,NaN,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,NaN,275.590101,NaN,NaN,NaN,NaN,0.865357,NaN,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.120000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,NaN,89.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [16]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

## Data Cleaning

In [17]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [19]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [20]:
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [21]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [27]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [26]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [28]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [29]:
correct_mapping = {
    # Clothing
    "T-shirt": "Clothing", "Shirt": "Clothing", "Shorts": "Clothing",
    "Hoodie": "Clothing", "Pants": "Clothing", "Socks": "Clothing",
    "Jeans": "Clothing", "Blouse": "Clothing", "Skirt": "Clothing",
    "Sweater": "Clothing", "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories", "Gloves": "Accessories",
    "Jewelry": "Accessories", "Hat": "Accessories",
    "Handbag": "Accessories", "Backpack": "Accessories",
    "Belt": "Accessories", "Scarf": "Accessories",
    "Bag": "Accessories",

    # Electronics
    "Laptop": "Electronics", "Phone": "Electronics",
    "Headphones": "Electronics", "Watch": "Electronics",

    # Footwear
    "Shoes": "Footwear", "Sandals": "Footwear",
    "Sneakers": "Footwear", "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear", "Jacket": "Outerwear"
}

In [30]:
df['Category']=df['Item Purchased'].map(correct_mapping)

In [31]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [32]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

## treating null value

In [35]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [39]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [40]:
# treating null values or replacing all values in the Electronics category
df.loc[df['Category']=='Electronics','Size']="Not Applicable"

In [41]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [44]:
# treating null values or replacing all values in the Accessories category
df.loc[df['Category']=='Accessories','Size']="Free Size"

In [45]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [46]:
# treating null values or replacing all values in the Footwear category
df.loc[df['Category']=='Footwear','Size']="Not Available"

In [47]:
df.groupby('Category')['Size'].unique()

Category
Accessories           [Free Size]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear          [Not Available]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [48]:
# treating null values or replacing all values in the Clothing category
df.loc[(df['Category']=='Clothing') & (df["Size"].isnull()),'Size']=df[df["Category"]=="Clothing"]["Size"].mode()[0]

In [49]:
df.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

# Review Ratting

In [50]:
df['Review Rating'].mean()

3.668195100022477

In [51]:
df['Review Rating'].median()

3.7

In [52]:
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [53]:
df.groupby("Item Purchased")["Review Rating"].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [54]:
# filling null values of Review Rating with the mean of each Item Purchase
df['Review Rating']=df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [55]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [56]:
df['Review Rating']=df['Review Rating'].round(2)

In [57]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.20,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.90,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.10,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.20,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.60,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.40,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.79,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,Free Size,Purple,Summer,4.00,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,Free Size,Red,Spring,4.30,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,Free Size,Yellow,Winter,2.80,Yes,Store Pickup,Yes,7.0,Cash,Monthly

# Previous Purchase

In [58]:
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

In [59]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

## Purchase Amount

In [60]:
df.groupby("Item Purchased")["Purchase Amount (USD)"].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [61]:
# filling null values of Purchase Amount (USD) with the mean of each Item Purchase
df['Purchase Amount (USD)']=df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [62]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

## Checking Duplicate

In [63]:
df.duplicated().sum()

50

In [64]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free Size,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,Not Available,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,Not Available,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Free Size,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Free Size,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Free Size,Peach,Summer,3.70,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Free Size,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Free Size,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Free Size,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Free Size,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Free Size,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,Not Available,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,Not Available,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,Not Available,Red,Winter,3.81,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Free Size,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Free Size,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,Not Available,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Free Size,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Free Size,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Free Size,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Free Size,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,Not Available,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Free Size,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Free Size,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,Not Available,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly

In [65]:
df[df['Customer ID']==974]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
483,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly

# Deleting Duplicate Record

In [66]:
len(df)

5050

In [67]:
df=df.drop_duplicates(subset=['Customer ID'],keep='first')

In [68]:
len(df)

5000

In [69]:
df.count()

Customer ID               5000
Age                       5000
Gender                    5000
Item Purchased            5000
Category                  5000
Purchase Amount (USD)     5000
Location                  5000
Size                      5000
Color                     5000
Season                    5000
Review Rating             5000
Subscription Status       5000
Shipping Type             5000
Discount Applied          5000
Previous Purchases        5000
Payment Method            5000
Frequency of Purchases    5000
dtype: int64

# Renaming the Header

In [70]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [71]:
df.columns= df.columns.str.replace(" ","_")

In [72]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='object')

In [73]:
df.columns= df.columns.str.lower()

df.columns

### replacing the purchase_amount_(usd) with purchase_amount

In [78]:
df=df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [79]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [80]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.20,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.90,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.10,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.20,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.60,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.40,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.79,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,Free Size,Purple,Summer,4.00,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,Free Size,Red,Spring,4.30,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,Free Size,Yellow,Winter,2.80,Yes,Store Pickup,Yes,7.0,Cash,Monthly

In [81]:
df['frequency_of_purchases'].unique()

array(['Weekly', 'Quarterly', 'Monthly', 'Annually', 'Every 3 Months',
       'Bi-Weekly', 'Fortnightly'], dtype=object)

# Connection to SQL Server

In [82]:
!pip install pymysql sqlalchemy pandas

Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (2.0.47)
Requirement already satisfied: pandas in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [83]:
from sqlalchemy import create_engine
import pandas as pd

# your credentials
username = "root"
password = ""      # use the password you set
host = "localhost"
port = "3306"
database = "Data_analysis"

# create connection
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# test connection
try:
    with engine.connect() as conn:
        print("✅ Connected to MySQL (Data_analysis)")
except Exception as e:
    print("❌ Error:", e)

✅ Connected to MySQL (Data_analysis)

In [84]:

engine = create_engine("mysql+pymysql://root:@localhost:3306/Data_analysis")

# upload to MySQL
df.to_sql("your_table", con=engine, if_exists="replace", index=False)

print("✅ CSV uploaded to MySQL")

✅ CSV uploaded to MySQL

In [87]:
dq = pd.read_sql("select * from customer",engine)
dq.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [90]:
!pip install ipython-sql

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: ipython in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython-sql) (8.37.0)
Requirement already satisfied: sqlalchemy>=2.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython-sql) (2.0.47)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython-sql) (1.17.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: decorator in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: exceptiongroup in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from stack_data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from stack_data->ipython->ipython-sql) (3.0.1)
Requirement already satisfied: pure-eval in /Users/mdshaqibhussain/Desktop/EVNS/venv310/lib/python3.10/site-packages (from stack_data->ipython->ipython-sql) (0.2.3)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: ipython-genutils, sqlparse, prettytable, ipython-sql
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [ipython-sql]
Successfully installed ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.17.0 sqlparse-0.5.5

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [91]:
%load_ext sql
%sql mysql+pymysql://root:@localhost/Data_analysis

In [93]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [94]:
%%sql
select * from customer limit 10;

 * mysql+pymysql://root:***@localhost/Data_analysis
10 rows affected.

[(2701, 22, 'Female', 'T-shirt', 'Clothing', 68.0, 'California', 'XL', 'Olive', 'Winter', 3.2, 'No', 'Standard', 'No', 36.0, 'Cash', 'Weekly'),
 (521, 51, 'Male', 'Sunglasses', 'Accessories', 84.0, 'South Carolina', 'Free Size', 'White', 'Spring', 3.9, 'Yes', 'Free Shipping', 'Yes', 20.0, 'Debit Card', 'Quarterly'),
 (3157, 18, 'Female', 'Shirt', 'Clothing', 50.0, 'Montana', 'M', 'Black', 'Winter', 3.1, 'No', '2-Day Shipping', 'No', 18.0, 'Cash', 'Monthly'),
 (1687, 22, 'Male', 'Gloves', 'Accessories', 75.0, 'Illinois', 'Free Size', 'Red', 'Fall', 4.2, 'No', 'Store Pickup', 'No', 25.0, 'Cash', 'Annually'),
 (2929, 40, 'Female', 'Jewelry', 'Accessories', 80.0, 'Alabama', 'Free Size', 'Yellow', 'Spring', 3.6, 'No', 'Store Pickup', 'No', 17.0, 'Credit Card', 'Weekly'),
 (3583, 23, 'Female', 'Shorts', 'Clothing', 41.0, 'California', 'S', 'Beige', 'Summer', 3.4, 'No', '2-Day Shipping', 'No', 15.0, 'PayPal', 'Annually'),
 (1135, 62, 'Male', 'T-shirt', 'Clothing', 81.0, 'Wisconsin', 'M', 'Brown', 'Summer', 3.79, 'No', 'Express', 'Yes', 2.0, 'Venmo', 'Every 3 Months'),
 (1411, 61, 'Male', 'Hat', 'Accessories', 93.0, 'Tennessee', 'Free Size', 'Purple', 'Summer', 4.0, 'No', 'Store Pickup', 'Yes', 18.0, 'Debit Card', 'Annually'),
 (113, 37, 'Male', 'Gloves', 'Accessories', 65.0, 'Florida', 'Free Size', 'Red', 'Spring', 4.3, 'Yes', 'Free Shipping', 'Yes', 28.0, 'PayPal', 'Bi-Weekly'),
 (166, 42, 'Male', 'Handbag', 'Accessories', 60.0, 'Kentucky', 'Free Size', 'Yellow', 'Winter', 2.8, 'Yes', 'Store Pickup', 'Yes', 7.0, 'Cash', 'Monthly')]

In [97]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

# Business Insights Questions

In [96]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:@localhost:3306/Data_analysis")

def q(sql):
    return pd.read_sql(sql, engine)

In [111]:
# which category generate highest revenue?
q("""
SELECT category, round(SUM(purchase_amount),2) AS Highest_revenue
FROM customer
GROUP BY category
ORDER BY Highest_revenue DESC;
""")

      category  Highest_revenue
0  Electronics        486366.96
1  Accessories        194866.87
2     Clothing        183188.39
3     Footwear        111236.20
4    Outerwear         18524.00

In [106]:
# are discount actually increase the purchase value?
q("""select discount_applied, 
    round(sum(purchase_amount),2) as total_revenue,
    round(avg(purchase_amount),2) as avg_purchase
    from customer
    group by discount_applied
    """)

  discount_applied  total_revenue  avg_purchase
0               No      502241.64        182.24
1              Yes      491940.78        219.22

In [107]:
# what is the total revenue generated by male and female customer?  
q(""" select gender,
    round(sum(purchase_amount),2) as total_revenue,
    round(avg(purchase_amount),2) as avg_purchase
    from customer
    group by gender;
    """)

   gender  total_revenue  avg_purchase
0  Female      352060.29        213.50
1    Male      390964.53        130.80
2   Other      251157.60        693.81

In [113]:
# whcih customer used a discount but still spent more then average purchase amount?
q(""" select customer_id,
    purchase_amount,
    discount_applied
    from customer
    where discount_applied='Yes' and purchase_amount > (select avg(purchase_amount) from customer) order by purchase_amount DESC limit 10;""")

   customer_id  purchase_amount discount_applied
0         4977          1499.76              Yes
1         4055          1493.56              Yes
2         4226          1472.22              Yes
3         4600          1460.51              Yes
4         4662          1459.59              Yes
5         4408          1456.31              Yes
6         5091          1451.07              Yes
7         4573          1441.51              Yes
8         4940          1439.75              Yes
9         4079          1438.53              Yes

In [117]:
# which are top/bottom 5 product with the highest review rating
q("""select item_purchased,
    round(avg(review_rating),2) as avg_ratings
    from customer
    group by item_purchased
    order by avg_ratings desc limit 5;""")

  item_purchased  avg_ratings
0         Gloves         3.86
1        Sandals         3.84
2          Boots         3.82
3            Hat         3.80
4          Skirt         3.79

In [118]:
q("""select item_purchased,
    round(avg(review_rating),2) as avg_ratings
    from customer
    group by item_purchased
    order by avg_ratings limit 5;""")

  item_purchased  avg_ratings
0          Phone         2.94
1     Headphones         3.08
2          Watch         3.10
3            Bag         3.17
4         Laptop         3.19

In [122]:
# Average purchase : standard vs Expres shipping
q("""select shipping_type,
    count(distinct customer_id) as order_placed,
    round(avg(purchase_amount),2) as avg_purchase,
    round(sum(purchase_amount),2) as total_revenue
    from customer
    group by shipping_type
    order by total_revenue desc;""")

    shipping_type  order_placed  avg_purchase  total_revenue
0         Express          1199        358.12      429380.98
1        Standard          1201        340.57      409020.45
2   Free Shipping           675         60.41       40777.00
3    Store Pickup           650         59.89       38931.00
4  2-Day Shipping           627         60.73       38080.00
5    Next Day Air           648         58.63       37993.00

In [128]:
# Do subscribe customer spend more ? or compare average spend and total revenue between the sub and not-sub
q("""select subscription_status,
    count(customer_id) as users,
    round(avg(purchase_amount),2) as avg_purchase,
    round(sum(purchase_amount),2) as total_revenue
    from customer
    group by subscription_status;""")

  subscription_status  users  avg_purchase  total_revenue
0                  No   3421        165.72      566937.02
1                 Yes   1579        270.58      427245.40

In [135]:
# top 5 products with highest discount usage % 
q("""select item_purchased,
    count(item_purchased) as number_of_item,
    count(case when discount_applied="yes" then 1 end) as number_of_time_sold_when_discount,
    count(case when discount_applied="yes" then 1 end)*100.0/count(*) as discount_percet_times
    from customer
    group by item_purchased
    order by discount_percet_times desc limit 5;""")

,item_purchased,number_of_item,number_of_time_sold_when_discount,discount_percet_times
0,Laptop,143,74,51.74825
1,Phone,171,88,51.46199
2,Headphones,166,85,51.20482
3,Hat,154,77,50.00000
4,Watch,157,78,49.68153

In [142]:
#segment customer into new returing and loyal based on their total number 
#of previous purchase,and show the count of each segment 
q("""
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_seg,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_seg;
""")

         customer_seg  customer_count
0      Loyal Customer            3085
1  Returning Customer            1354
2        New Customer             561

In [148]:
#what are the top 3 most purchase products within each category ?
q("""with cte as(
    select category,item_purchased,
    count(item_purchased) as most_purchased,
    rank() over(partition by category order by count(item_purchased) desc) as rnk
    from customer
    group by category,item_purchased)
    select * from cte where rnk<=3
    ;""")

       category item_purchased  most_purchased  rnk
0   Accessories        Jewelry             171    1
1   Accessories            Bag             164    2
2   Accessories     Sunglasses             161    3
3   Accessories           Belt             161    3
4      Clothing          Shirt             315    1
5      Clothing          Pants             171    2
6      Clothing         Blouse             171    2
7   Electronics          Phone             171    1
8   Electronics     Headphones             166    2
9   Electronics          Watch             157    3
10     Footwear          Shoes             303    1
11     Footwear        Sandals             160    2
12     Footwear       Sneakers             145    3
13    Outerwear         Jacket             163    1
14    Outerwear           Coat             161    2

In [153]:
# are customer who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
q("""select 
    case
        when previous_purchases>5 then 'Repeat Buyers'
        else 'Normal Buyers'
    end as customer_type,
    subscription_status,
    count(*) as customer_count
    from customer
    group by customer_type,subscription_status;""")

   customer_type subscription_status  customer_count
0  Repeat Buyers                  No            2763
1  Repeat Buyers                 Yes            1190
2  Normal Buyers                  No             658
3  Normal Buyers                 Yes             389

In [158]:
# what is the revenue contribution of each age group ?
q("""select
    case
        when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 50 then '36-50'
        else '50+'
    end as age_group,
    round(sum(purchase_amount),2) as total_revenu
    from customer
    group by age_group
    order by total_revenu desc;""")

  age_group  total_revenu
0       50+     399345.32
1     36-50     266706.70
2     26-35     177421.93
3     18-25     150708.48

In [159]:
df = pd.read_sql("SELECT * FROM customer", engine)
df.to_csv("customer.csv", index=False)